http:
    host: localhost
    port: 8090
logger:
    addsource: false
    # debug = -4
	# info = 0
	# warn = 4
	# error = 8
    level: 0
mysql:
    database: swtest
    host: localhost
    password: qwer
    port: 3306
    user: root
    debug: false
jwt:
    # unit: minute
    expiration: 5